Repository NJITICC/awesome-nicc, pull requests merged in 2024-11, with the labels that each got.

#10 feat: add Cybersecurity Guide
  software/cybersecurity-guide.yml
Labels: addition

#11 feat: add oletools
  software/oletools.yml
Labels: addition

#12 feat: add WhatWeb
  software/whatweb.yml
Labels: addition

#13 feat: add links to main site
  .hecat/conf.py
  Makefile
  _templates/page.html
  _templates/sidebar/brand.html
  markdown/header.md
Labels: enhancement

#15 fix: makefile for windows
  Makefile
Labels: bug

#16 feat: add splunk link
  software/splunkwork+.yml
Labels: addition
